<?php

use App\Jobs\ProvisionServerJob;
use App\Models\Product;
use App\Models\User;
use App\Services\OrderService;
use App\Services\PaymentService;
use Illuminate\Support\Facades\Artisan;

Artisan::command('app:demo-order', function () {
    $this->call('db:seed', ['--force' => true]);

    $user = User::query()->firstOrCreate(
        ['email' => 'demo@example.com'],
        ['name' => 'Demo Customer', 'password' => 'password', 'locale' => 'en']
    );

    $product = Product::query()->where('slug', 'vps-cx21')->firstOrFail();

    $this->info('Placing order for '.$product->name.' ('.$product->billing_cycle.' cycle)...');

    $order = app(OrderService::class)->place($user, $product);
    $invoice = app(OrderService::class)->createInvoice($order, 'manual');
    $payment = app(PaymentService::class)->start($invoice, 'manual');

    $this->info('Invoice '.$invoice->invoice_number.' created ('.$invoice->amount_toman.' toman).');
    $this->info('Confirming payment via ManualGateway...');

    app(PaymentService::class)->confirm($payment, ['approved' => true]);
    ProvisionServerJob::dispatchSync($order->fresh());

    $order->refresh();
    $server = $order->server;

    $this->newLine();
    $this->info('✅ Order '.$order->order_number.' → '.$order->status);
    $this->info('✅ Server '.$server->provider_server_id.' — IP '.$server->ip_address.' — status '.$server->status);
    $this->info('   Specs: '.($server->plan_snapshot['vcpu'] ?? '?').' vCPU / '.($server->plan_snapshot['ram_mb'] ?? '?').' MB RAM');
    $this->info('   Cost snapshot: '.number_format($server->selling_price ?? 0).' toman (margin '.number_format($server->gross_margin ?? 0).')');
    $this->info('   Expires: '.$server->expires_at);

    $this->newLine();
    $this->warn('Root password was generated by the provider and stored encrypted; it is not printed here.');
})->purpose('Demo the FakeProvider provisioning flow end-to-end');
